### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Jet004**

### CODE REVIEW

**Review by B08waffles — COMMENTED** [review]
Some sensible defaults here that should help us progress in the long term

**Review by galarist — APPROVED** [review]

**Review by galarist — APPROVED** [review]

**Review by Claire-bk — APPROVED** [review]

**Review by Claire-bk — APPROVED** [review]

**Review by B08waffles — COMMENTED** [review]
Should be good to go!

**Review by B08waffles — APPROVED** [review]

**Comment by 2016lisali** [comment]
Looks great.

**Review by 2016lisali — COMMENTED** [review]
Great work, thanks, Jacob.

**Pull request merged**
